name: Java CI
on: push
env:
  GIT_COMMIT: ${{ github.sha }}
jobs:
  clone:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs:
      - clone
    steps:
      - name: Dowmnload Artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Build App
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs:
      - clone
    steps:
      - name: Dowmnload Artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh

  component-test:
    runs-on: ubuntu-latest
    needs:
      - push-docker-hub
    steps:
      - name: Dowmnload Artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Component Test
        run: chmod +x ci/component-test.sh && GIT_COMMIT="GA-$GITHUB_SHA" && ci/component-test.sh

  performance-test:
    runs-on: ubuntu-latest
    needs:
      - push-docker-hub
    steps:
      - name: Dowmnload Artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Performance Test
        run: chmod +x ci/performance-test.sh && GIT_COMMIT="GA-$GITHUB_SHA" && ci/performance-test.sh

  push-docker-hub:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Dowmnload Artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: $docker_username/micronaut-app:1.0-${GIT_COMMIT::8}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
