name: Java CI
on: push
jobs:
  clone:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs:
      - clone
    steps:
      - name: Dowmnload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
      - name: Build App
        run: ci/build-app.sh

  test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs:
      - clone
    steps:
      - name: Dowmnload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
      - name: Test
        run: ci/unit-test-app.sh
